export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1af6ed96": [() => import(/* webpackChunkName: "1af6ed96" */ "@site/i18n/my/docusaurus-plugin-content-docs/current/02-page-1.md"), "@site/i18n/my/docusaurus-plugin-content-docs/current/02-page-1.md", require.resolveWeak("@site/i18n/my/docusaurus-plugin-content-docs/current/02-page-1.md")],
  "3d696927": [() => import(/* webpackChunkName: "3d696927" */ "@generated/docusaurus-plugin-content-docs/default/p/my-b01.json"), "@generated/docusaurus-plugin-content-docs/default/p/my-b01.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/my-b01.json")],
  "535e25d1": [() => import(/* webpackChunkName: "535e25d1" */ "@site/i18n/my/docusaurus-plugin-content-docs/current/06-page-5.md"), "@site/i18n/my/docusaurus-plugin-content-docs/current/06-page-5.md", require.resolveWeak("@site/i18n/my/docusaurus-plugin-content-docs/current/06-page-5.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "6282f1fb": [() => import(/* webpackChunkName: "6282f1fb" */ "@site/i18n/my/docusaurus-plugin-content-docs/current/04-page-3.md"), "@site/i18n/my/docusaurus-plugin-content-docs/current/04-page-3.md", require.resolveWeak("@site/i18n/my/docusaurus-plugin-content-docs/current/04-page-3.md")],
  "693d4171": [() => import(/* webpackChunkName: "693d4171" */ "@site/i18n/my/docusaurus-plugin-content-docs/current/03-page-2.md"), "@site/i18n/my/docusaurus-plugin-content-docs/current/03-page-2.md", require.resolveWeak("@site/i18n/my/docusaurus-plugin-content-docs/current/03-page-2.md")],
  "7b0532ad": [() => import(/* webpackChunkName: "7b0532ad" */ "@site/i18n/my/docusaurus-plugin-content-docs/current/01-home.md"), "@site/i18n/my/docusaurus-plugin-content-docs/current/01-home.md", require.resolveWeak("@site/i18n/my/docusaurus-plugin-content-docs/current/01-home.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "dfd441e1": [() => import(/* webpackChunkName: "dfd441e1" */ "@site/i18n/my/docusaurus-plugin-content-docs/current/05-page-4.md"), "@site/i18n/my/docusaurus-plugin-content-docs/current/05-page-4.md", require.resolveWeak("@site/i18n/my/docusaurus-plugin-content-docs/current/05-page-4.md")],};
